[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Future of Transportation: How Artificial Intelligence and Other Technologies Will Transform the Way We Move"
